### PR TITLE
Add h26x decoder support

### PR DESCRIPTION
**Pull request by gBillal**
Hi, thanks for creating this project. I have always wanted something to use for decoding videos without the need to rely on membrane pipelines.

In this PR, I added support for `h264/h265` decoders. Unlike `vp8` where there's no notion of B frames and to not change the public API of the decoder since the decoder can return multiple frames at the same time, I added a `flush/1` function to signals end of stream and get the buffered frames in the decoder.

### CODE REVIEW

**Review by mickel8 — APPROVED** [review]
Awesome, thanks!

**Comment by mickel8** [comment]
Released as 0.8.0 :)

**Comment by mickel8** [comment]
Btw @gBillal, how did you generated h264 and h265 frames? It would be nice to write this down somewhere :P

**Comment by gBillal** [comment]
For that I just grabbed the first sample from a valid mp4 file (the famous BigBuck). An easier way to do that is to use ffmpeg
```bash
# h264
ffmpeg -i your_mp4_file.mp4 -c:v copy -vframes 1 -f h264 sample.h264

# h265
ffmpeg -i your_mp4_file.mp4 -c:v copy -vframes 1 -f hevc sample.h265
```

**Pull request merged**
